#server:
#  port: 8820

spring:
  data:
    mongodb:
      uri: mongodb://192.168.0.207:27017
      database: agc_cdm
  profiles:
    active: dev
  mail:
    host: smtp.gmail.com
    port: 587
    username: dahamyuth06@gmail.com
    password: Zaq1xsw2@1983
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

logging:
  level:
    org.springframework.web: ERROR
    com.archisoft.demo.buznature: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} -%msg%n"
  file: /home/tharanga/workspace/archisoft/demo/log/DemoMTxBuznature-archisoft.log

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

message:  dev-environment
