server:
  port: 8899

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  profiles:
    active: dev

    #server:
    #port: 8899

spring:
  data:
    mongodb:
      uri: mongodb://192.168.0.207:27017
      database: agc_uaa
